### ISSUE TITLE
ImportError: No module named 'pyxaudio.ffmpeg'

### ISSUE THREAD

**Issue by raphaelyancey** [gustaebel/pyxaudio#1]
Hi, I'm trying to use your lib but I'm getting an error when running the beep example.

> pulseaudio 10.0
> ffmpeg 3.2.9
> alsa-utils 1.0.28
> Python 3.4
> Cython 0.27.3

```
pi@raspberry:~/pyxaudio $ python3 beep
Traceback (most recent call last):
  File "beep", line 8, in <module>
    import pyxaudio
  File "/home/pi/pyxaudio/pyxaudio/__init__.py", line 24, in <module>
    from pyxaudio.ffmpeg import FFmpegSource
ImportError: No module named 'pyxaudio.ffmpeg'
```

The building went well and I got the following files in `pyxaudio/`
`alsa.c  alsa.pxd  alsa.pyx  ffmpeg.c  ffmpeg.pxd  ffmpeg.pyx  __init__.py  __init__.pyc  pulse.c  pulse.pxd  pulse.pyx  __pycache__  _shared.py  _sink.c  _sink.pxd  _sink.pyx`

Same with `python2`.

Any idea?

**Comment by gustaebel** [comment]
Have you tried building it with `python setup.py build_ext --inplace`?
